[package]
name = "TurbosAUMOracle"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework", rev = "devnet" }

[addresses]
turbos_aum_oracle = "_"

[dev-addresses]
turbos_aum_oracle = "0x0"